services:
  web:
    depends_on:
      - server
    build:
      context: .
    restart: always
    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./
          target: /usr/src/app
          action: sync
          ignore:
            - node_modules/
        - path: ./package.json
          action: rebuild

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mydatabase']
      interval: 10s
      retries: 5

  server:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./server
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      DATABASE_URL: ${DB_URL}

    develop:
      watch:
        - path: ./server
          target: /usr/src/app/server
          action: rebuild
          ignore:
            - node_modules/
        - path: ./server/package.json
          action: rebuild
